apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-traffic-split
  namespace: so1-fase2
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.monitor.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-python-service
                port:
                  number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-main
  namespace: so1-fase2
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.monitor.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-nodejs-service
                port:
                  number: 3000