apiVersion: v1
kind: Service
metadata:
  name: api-python-service
  namespace: so1_fase2
  labels:
    app: api-python
    route: python
spec:
  selector:
    app: api-python
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP