apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-api
  namespace: so1-fase2
  labels:
    app: websocket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-api
  template:
    metadata:
      labels:
        app: websocket-api
    spec:
      containers:
      - name: websocket-api
        image: bismarckr/websocket-api-fase2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: "host.minikube.internal"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "monitor"
        - name: DB_PASSWORD
          value: "monitor123"
        - name: DB_NAME
          value: "monitoring"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"