apiVersion: v1
kind: Service
metadata:
  name: websocket-api-service
  namespace: so1-fase2
  labels:
    app: websocket-api
spec:
  selector:
    app: websocket-api
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP