apiVersion: v1
kind: Service
metadata:
  name: websocket-api-service
  namespace: so1-fase2
  labels:
    app: websocket-api
spec:
  selector:
    app: websocket-api
  ports:
    - name: ws
      port: 4000
      targetPort: 4000
      protocol: TCP
    - name: http
      port: 80
      targetPort: 4000
      protocol: TCP
    - name: ext-8080
      port: 8080
      targetPort: 4000
      protocol: TCP
  type: LoadBalancer