apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: so1_fase2
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS monitoring;
    USE monitoring;

    CREATE TABLE IF NOT EXISTS cpu_metrics (
        id INT AUTO_INCREMENT PRIMARY KEY,
        timestamp INT NOT NULL,
        porcentaje_uso DECIMAL(5,2) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_timestamp (timestamp)
    );

    CREATE TABLE IF NOT EXISTS ram_metrics (
        id INT AUTO_INCREMENT PRIMARY KEY,
        timestamp INT NOT NULL,
        total BIGINT NOT NULL,
        libre BIGINT NOT NULL,
        uso BIGINT NOT NULL,
        porcentaje_uso DECIMAL(5,2) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_timestamp (timestamp)
    );

    CREATE TABLE IF NOT EXISTS procesos_metrics (
        id INT AUTO_INCREMENT PRIMARY KEY,
        timestamp INT NOT NULL,
        procesos_corriendo INT NOT NULL,
        total_processos INT NOT NULL,
        procesos_durmiendo INT NOT NULL,
        procesos_zombie INT NOT NULL,
        procesos_parados INT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_timestamp (timestamp)
    );

    CREATE TABLE IF NOT EXISTS metrics_cache (
        id VARCHAR(50) PRIMARY KEY,
        timestamp INT NOT NULL,
        data JSON NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    INSERT IGNORE INTO metrics_cache (id, timestamp, data) VALUES 
    ('cpu', UNIX_TIMESTAMP(), '{"porcentaje_uso": 0}'),
    ('ram', UNIX_TIMESTAMP(), '{"total": 0, "libre": 0, "uso": 0, "porcentaje_uso": 0}'),
    ('procesos', UNIX_TIMESTAMP(), '{"procesos_corriendo": 0, "total_processos": 0, "procesos_durmiendo": 0, "procesos_zombie": 0, "procesos_parados": 0}');