apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nodejs
  namespace: so1-fase2
  labels:
    app: api-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-nodejs
  template:
    metadata:
      labels:
        app: api-nodejs
    spec:
      containers:
      - name: api-nodejs
        image: bismarckr/api-nodejs-fase2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "host.minikube.internal"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "monitor"
        - name: DB_PASSWORD
          value: "monitor123"
        - name: DB_NAME
          value: "monitoring"
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"