apiVersion: v1
kind: Service
metadata:
  name: api-nodejs-service
  namespace: so1-fase2
  labels:
    app: api-nodejs
spec:
  selector:
    app: api-nodejs
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP